spring:
  datasource: #mysql 配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://{}?useSSL=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai #数据库URL
    username: username #用户名
    password: password #密码
  data: # redis配置
    redis:
      database: 0
      host: 127.0.0.1
      lettuce:
        pool:
          max-active: -1 #最大连接数据库连接数,设 -1 为没有限制
          max-idle: 0    #最大等待连接中的数量,设 0 为没有限制
          max-wait: -1ms #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制
          min-idle: 0    #最小等待连接中的数量,设 0 为没有限制
        shutdown-timeout: 100ms
      password: ''
      port: 6379
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
server: # 端口设置
  port: 8081

# 日志持久化路径,只有部署的时候需要
logging:
  file:
    path: "/home/ubuntu"

expirationTime: 1000  # redis缓存过期时间(秒)
imagePath: "/home/ubuntu/BSDN/image/" # 存储图片路径
videoPath: "/home/ubuntu/BSDN/video/" # 存储视频路径
tokenLength: 10 #token长度
logicIndexPath: "URL" #登录页面
BaseUrl: URL # 基本URL
PageSize: 5 # 每一页显示的数据量